using System.Text.RegularExpressions;
using System.IO.Hashing;
using System.Text;

string protoFile = args.Length > 0 ? args[0] : "Message.proto";
string outputDir = args.Length > 1 ? args[1] : "MsgMeta";

var proto = File.ReadAllText(protoFile);
var matches = Regex.Matches(proto, @"^message\s+(\w+)", RegexOptions.Multiline);

var names = matches.Select(m => m.Groups[1].Value)
                   .Where(n => n != "MessageReflection")
                   .OrderBy(n => n)
                   .ToList();

// ---- 生成 MsgCmdId.g.cs ----
var cmdIdLines = new StringBuilder();
cmdIdLines.AppendLine("// <auto-generated>");
cmdIdLines.AppendLine("public static class MsgCmdId");
cmdIdLines.AppendLine("{");
foreach (var name in names)
{
    var hash = Crc32.Hash(Encoding.UTF8.GetBytes(name));
    uint id = BitConverter.ToUInt32(hash);
    cmdIdLines.AppendLine($"    public const uint {name} = {id};");
}
cmdIdLines.AppendLine("}");

File.WriteAllText(Path.Combine(outputDir, "MsgCmdId.g.cs"), cmdIdLines.ToString());
Console.WriteLine($"生成 MsgCmdId.g.cs — {names.Count} 个消息");

// ---- 生成 MsgMetaInitializer.g.cs ----
var initLines = new StringBuilder();
initLines.AppendLine("// <auto-generated>");
initLines.AppendLine("using System;");
initLines.AppendLine("using System.Collections.Generic;");
initLines.AppendLine();
initLines.AppendLine("public static class MsgMetaInitializer");
initLines.AppendLine("{");
initLines.AppendLine("    public static MsgMeta Init(this MsgMeta meta)");
initLines.AppendLine("    {");
initLines.AppendLine("        meta.items = new MsgMetaItem[]");
initLines.AppendLine("        {");

for (int i = 0; i < names.Count; i++)
{
    var isRsp = names[i].StartsWith("Rsp") || names[i] == "Pong";
    initLines.AppendLine($"            new MsgMetaItem(MsgCmdId.{names[i]}, {names[i]}.Parser, {(isRsp ? "true" : "false")}),");
}

initLines.AppendLine("        };");
initLines.AppendLine();
initLines.AppendLine("        meta.cmdIdToItem = new Dictionary<uint, MsgMetaItem>");
initLines.AppendLine("        {");
for (int i = 0; i < names.Count; i++)
{
    initLines.AppendLine($"            {{MsgCmdId.{names[i]}, meta.items[{i}]}},");
}
initLines.AppendLine("        };");
initLines.AppendLine();
initLines.AppendLine("        meta.typeToItem = new Dictionary<Type, MsgMetaItem>");
initLines.AppendLine("        {");
for (int i = 0; i < names.Count; i++)
{
    initLines.AppendLine($"            {{typeof({names[i]}), meta.items[{i}]}},");
}
initLines.AppendLine("        };");
initLines.AppendLine();
initLines.AppendLine("        return meta;");
initLines.AppendLine("    }");
initLines.AppendLine("}");

File.WriteAllText(Path.Combine(outputDir, "MsgMetaInitializer.g.cs"), initLines.ToString());
Console.WriteLine($"生成 MsgMetaInitializer.g.cs — 完成");
